### ISSUE TITLE
Which update site is correct? Bioformats or BigDataviewer

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#15]
By accident I found that there also a version of the plugin on the Bioformats update site. That's confusing as hell. Why is it on 2 update sites? Please stick to one update site.

**Comment by StephanPreibisch** [comment]
It should only be on the main Fiji update site, nowhere else. @tpietzsch @hinerm - do you have any idea how that comes? Thanks a lot, Stephan

**Comment by hinerm** [comment]
@StephanJanosch @StephanPreibisch The Bio-Formats update site ships Bio-Formats 5.1, which is not yet released. Since core Fiji ships the stable Bio-Formats 5.0.x line, anything that uses Bio-Formats needs to be updated for the 5.1 API when the Bio-Formats site is enabled - otherwise it would break.

Because @ctrueden is awesome, he made Bio-Formats 5.1 [development branches](https://github.com/bigdataviewer/SPIM_Registration/tree/ome-5.1) for everything that needed them. So these are what ship on the Bio-Formats update site.

**Comment by StephanJanosch** [comment]
Okay...good to know. Thanks all.
