### ISSUE TITLE
Deconvolution looks at wrong directory for CUDA lib

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#23]
What it did
```
Looking for native libraries ending with '.so', '.lib' in directory: '/projects/wormspim2/worm7/worm7' ... 
Trying to load following library: /projects/wormspim2/worm7/worm7/libFourierConvolutionCUDALib.so
```

What I told to do:
```
"compute_on=[GPU (Nvidia CUDA via JNA)] "+
"directory=/sw/users/janosch/lib "+
"select_native_library_for_cudafourierconvolution=libFourierConvolutionCUDALib.so "+
"gpu_1 "+
```

**Comment by StephanPreibisch** [comment]
I suspect a problem with the macro call itself. It works fine when I run it on my computer.

**Comment by StephanJanosch** [comment]
Sure it works fine on the workstation here too. But the recorded macro does something else.

I just recorded the macro with the lastest version. I will check again.

But Christopher Schmied did sent you an email about this issue in the past too. I will ask him, to put his analysis of the problem here.

**Comment by schmiedc** [comment]
Hi Stephan, 

I observed the same issue: 
I specify the directory for the libraries via this line in the macro:

"directory=[/sw/users/schmied/packages/Fiji.app.cuda_new/lib/] " +

But instead of using this directory it searches the libraries in the output_file_directory. Here shown in the output file (full output file attached: deco.out):

"Looking for native libraries ending with '.so', '.lib' in directory: '/projects/pilot_spim/Christopher/Test_pipeline_3.0' ...
Trying to load following library: /projects/pilot_spim/Christopher/Test_pipeline_3.0/libFourierConvolutionCUDALib.so"

When recording the macro locally there was one message I got from the recorder:

![keyword_deconvolution](https://cloud.githubusercontent.com/assets/10744409/7136889/51bbf704-e2b5-11e4-9054-e9135ea533dc.png)

Which tells me that the keyword "directory" is duplicated. It also tells me that I should add an underscore to the corresponding label to make the first word unique. 

Full macro for deconvolution
--- 
// Load Fiji dependencies
import ij.IJ;
import ij.ImagePlus;
import java.lang.Runtime;
import java.io.File;
import java.io.FilenameFilter;
 
runtime = Runtime.getRuntime();
System.out.println(runtime.availableProcessors() + " cores available for multi-threading");

System.out.println( "Start to load Parameters:" );

// Select xml
image_file_directory = System.getProperty( "image_file_directory" );
merged_xml = System.getProperty( "merged_xml" );

// Load general Parameters
parallel_timepoints = System.getProperty( "parallel_timepoints" );
process_timepoint = System.getProperty( "process_timepoint" );
process_channel = System.getProperty( "process_channel" );
process_illumination = System.getProperty( "process_illumination" );
process_angle = System.getProperty( "process_angle" ); 

// Load bounding box
minimal_x_deco = System.getProperty( "minimal_x_deco" );
minimal_y_deco = System.getProperty( "minimal_y_deco" );
minimal_z_deco = System.getProperty( "minimal_z_deco" );
maximal_x_deco = System.getProperty( "maximal_x_deco" );
maximal_y_deco = System.getProperty( "maximal_y_deco" );
maximal_z_deco = System.getProperty( "maximal_z_deco" );

// Load deconvolution Parameters

deco_output_file_directory = System.getProperty( "deco_output_file_directory" );
directory_cuda = System.getProperty( "directory_cuda" );

// Print parameters into output file
System.out.println( "-------------------------------------------------------" );
System.out.println( "Load xml file: " );
System.out.println( "selected_xml = " + image_file_directory + merged_xml + ".xml");
System.out.println( "-------------------------------------------------------" );
System.out.println( "General parameters: " );
System.out.println( "parallel_timepoints = " + parallel_timepoints );
System.out.println( "process_timepoints = " + process_timepoint ); 
System.out.println( "process_channel = " + process_channel );
System.out.println( "process_illumination = " + process_illumination );
System.out.println( "process_angle = " + process_angle );
System.out.println( "-------------------------------------------------------" );
System.out.println( "Bounding box: " );
System.out.println( "minimal_x_deco = " + minimal_x_deco );
System.out.println( "minimal_y_deco = " + minimal_y_deco );
System.out.println( "minimal_z_deco = " + minimal_z_deco );
System.out.println( "maximal_x_deco = " + maximal_x_deco );
System.out.println( "maximal_y_deco = " + maximal_y_deco );
System.out.println( "maximal_z_deco = " + maximal_z_deco );
System.out.println( "-------------------------------------------------------" );
System.out.println( "CUDA: " );
System.out.println( "deco_output_file_directory = " + deco_output_file_directory );
System.out.println( "directory_cuda = " + directory_cuda );
	
// Execute Fiji Plugin
System.out.println( "=======================================================" );
System.out.println( "Starting Deconvolution" );

IJ.run("Fuse/Deconvolve Dataset", 
	"select_xml=" + image_file_directory + merged_xml + ".xml " + 
	"process_angle=[All angles] " +
	"process_channel=[All channels] " + 
	"process_illumination=[All illuminations] " +
	"process_timepoint=[All Timepoints] " +
	"type_of_image_fusion=[Multi-view deconvolution] " +
	"bounding_box=[Define manually] " +
	"fused_image=[Save as TIFF stack] " +
	"minimal_x=56 " +
	"minimal_y=8 " +
	"minimal_z=-220 " +
	"maximal_x=504 " + 
	"maximal_y=960 " + 
	"maximal_z=236 " +
	"imglib2_container=ArrayImg " +
	"type_of_iteration=[Efficient Bayesian - Optimization I (fast, precise)] " +
	"osem_acceleration=[1 (balanced)] " +
	"number_of_iterations=1 " +
//	"adjust_blending_parameters " +
	"use_tikhonov_regularization " +
	"tikhonov_parameter=0.0060 " +
	"compute=[in 512x512x512 blocks] " +
	"compute_on=[GPU (Nvidia CUDA via JNA)] " +
	"psf_estimation=[Extract from beads] " +
	"psf_display=[Do not show PSFs] " +
	"output_file_directory=" + deco_output_file_directory + " " +
	"directory=[/sw/users/schmied/packages/Fiji.app.cuda_new/lib/] " +
//	"directory=[" + directory_cuda + "] " +
	"select_native_library_for_cudafourierconvolution=libFourierConvolutionCUDALib.so " + 
	"gpu_1 " +
//	"gpu_2 " + 
	"detections_to_extract_psf_for_channel_0=beads " +
	"psf_size_x=19 " +
	"psf_size_y=19 " +
	"psf_size_z=25");

/* shutdown */
runtime.exit(0);

---
[schmied@madmax deconvolution]$ cat out*
Sender: LSF System <hpcadmin@n42>
Subject: Job 990995: <./deconvolution-2.job> in cluster scuba_cluster1 Done

Job <./deconvolution-2.job> was submitted from host <madmax> by user <schmied> in cluster <scuba_cluster1>.
Job was executed on host(s) <n42>, in queue <gpu>, as user <schmied> in cluster <scuba_cluster1>.
</home/schmied> was used as the home directory.
</projects/pilot_spim/Christopher/pipeline_3.0/jobs_alpha_3.0/deconvolution> was used as the working directory.
Started at Wed Mar 25 15:10:08 2015
Results reported at Wed Mar 25 15:15:26 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
./deconvolution-2.job
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :   2229.61 sec.
    Max Memory :     20304 MB
    Max Swap   :    266085 MB

    Max Processes  :         6
    Max Threads    :        45

The output (if any) follows:

12 cores available for multi-threading
Start to load Parameters:
-------------------------------------------------------
Load xml file: 
selected_xml = /projects/pilot_spim/Christopher/Test_pipeline_3.0/His-YFP_Test_merged.xml
-------------------------------------------------------
General parameters: 
parallel_timepoints = 2
process_timepoints = Single Timepoint (Select from List)
process_channel = All channels
process_illumination = All illuminations
process_angle = All angles
-------------------------------------------------------
Bounding box: 
minimal_x_deco = 112
minimal_y_deco = 16
minimal_z_deco = -440
maximal_x_deco = 1008
maximal_y_deco = 1920
maximal_z_deco = 472
-------------------------------------------------------
CUDA: 
deco_output_file_directory = /projects/pilot_spim/Christopher/Test_pipeline_3.0/
directory_cuda = /sw/users/schmied/packages/Fiji.app.cuda_new/lib/
=======================================================
Starting Deconvolution
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.1.1-SNAPSHOT
angles selected: 1, 2, 3, 4, 5
channels selected: 0
illuminations selected: 0
Timepoints selected: 2
Wed Mar 25 15:10:14 CET 2015: Estimating Bounding Box for Fusion. If size of images is not known (they were never opened before), some of them need to be opened once to determine their size.
Looking for native libraries ending with '.so', '.lib' in directory: '/projects/pilot_spim/Christopher/Test_pipeline_3.0' ... 
Trying to load following library: /projects/pilot_spim/Christopher/Test_pipeline_3.0/libFourierConvolutionCUDALib.so
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using device Tesla M2090 (id=0, mem=5375MB (5375MB free), CUDA capability 2.0)
beads --- channel: 0 angle: 1 illum: 0 timepoint: 2: 1154 correspondences.
beads --- channel: 0 angle: 2 illum: 0 timepoint: 2: 944 correspondences.
beads --- channel: 0 angle: 3 illum: 0 timepoint: 2: 1050 correspondences.
beads --- channel: 0 angle: 4 illum: 0 timepoint: 2: 945 correspondences.
beads --- channel: 0 angle: 5 illum: 0 timepoint: 2: 931 correspondences.

Found 1 label(s) with correspondences for channel 0: 
Label 'beads' (channel 0) has 5/5 views with corresponding detections.
Channel 0: extract PSF from label 'beads'
Fusing view 0 of 4
(Wed Mar 25 15:10:14 CET 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 0 using label 'beads' (468 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 1 of 4
(Wed Mar 25 15:10:32 CET 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 1 using label 'beads' (346 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 2 of 4
(Wed Mar 25 15:11:18 CET 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 2 using label 'beads' (378 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 3 of 4
(Wed Mar 25 15:12:06 CET 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 3 using label 'beads' (388 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 4 of 4
(Wed Mar 25 15:12:51 CET 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 4 using label 'beads' (291 corresponding detections available)
PSF size: (19, 19, 25)
Minimal number of overlapping views: 0, using 1
Average number of overlapping views: 2.2430509773190668, using 2.2430509773190668
Type of iteration: OPTIMIZATION_I
Number iterations: 1
OSEM speedup: 1.0
Using blocks: true
Block size: (512, 512, 512)
Using CUDA: true
Blending border: 9x9x5
Blending range: 25x25x25
PSF size (extracting): 19x19x25
Channel 0 extracts from label 'beads'. 
ImgLib container (deconvolved): ArrayImgFactory
Using Tikhonov regularization (lambda = 0.0060)
imgSize (449, 953, 457)
kernelSize (11, 11, 63)
blockSize (512, 512, 512)
numBlocks (1, 2, 2)
effectiveSize (502, 502, 450)
effectiveLocalOffset (5, 5, 31)
Number of blocks: 4
imgSize (449, 953, 457)
kernelSize (63, 11, 29)
blockSize (512, 512, 512)
numBlocks (1, 2, 1)
effectiveSize (450, 502, 484)
effectiveLocalOffset (31, 5, 14)
Number of blocks: 2
imgSize (449, 953, 457)
kernelSize (45, 11, 57)
blockSize (512, 512, 512)
numBlocks (1, 2, 2)
effectiveSize (468, 502, 456)
effectiveLocalOffset (22, 5, 28)
Number of blocks: 4
imgSize (449, 953, 457)
kernelSize (45, 11, 57)
blockSize (512, 512, 512)
numBlocks (1, 2, 2)
effectiveSize (468, 502, 456)
effectiveLocalOffset (22, 5, 28)
Number of blocks: 4
imgSize (449, 953, 457)
kernelSize (63, 11, 29)
blockSize (512, 512, 512)
numBlocks (1, 2, 1)
effectiveSize (450, 502, 484)
effectiveLocalOffset (31, 5, 14)
Number of blocks: 2
Wed Mar 25 15:13:45 CET 2015: numThreads = 12
Wed Mar 25 15:14:11 CET 2015: done normalizing.
Min number of overlapping views: 1
Average number of overlapping views: 2.327602872744051
Average intensity in overlapping area: 0.5058642
OSEM acceleration: 1.0
Deconvolved image container: ArrayContainerFactory
iteration: 0 (Wed Mar 25 15:14:13 CET 2015)
 block 0(CPU  0): copy 194
 block 0(CUDA 0): compute 1766
 block 0(CPU  0): paste 67
 block 1(CPU  0): copy 170
 block 1(CUDA 0): compute 1228
 block 1(CPU  0): paste 40
 block 2(CPU  0): copy 237
 block 2(CUDA 0): compute 1033
 block 2(CPU  0): paste 2
 block 3(CPU  0): copy 237
 block 3(CUDA 0): compute 1228
 block 3(CPU  0): paste 2
0 a: -6390 ms.
0 b: -5723 ms.
 block 0(CPU  0): copy 216
 block 0(CUDA 0): compute 1228
 block 0(CPU  0): paste 40
 block 1(CPU  0): copy 220
 block 1(CUDA 0): compute 1038
 block 1(CPU  0): paste 41
1 a: -3215 ms.
1 b: -2945 ms.
 block 0(CPU  0): copy 140
 block 0(CUDA 0): compute 1227
 block 0(CPU  0): paste 44
 block 1(CPU  0): copy 148
 block 1(CUDA 0): compute 1032
 block 1(CPU  0): paste 39
 block 2(CPU  0): copy 238
 block 2(CUDA 0): compute 1030
 block 2(CPU  0): paste 2
 block 3(CPU  0): copy 260
 block 3(CUDA 0): compute 1033
 block 3(CPU  0): paste 2
2 a: -5479 ms.
2 b: -5812 ms.
 block 0(CPU  0): copy 208
 block 0(CUDA 0): compute 1036
 block 0(CPU  0): paste 45
 block 1(CPU  0): copy 172
 block 1(CUDA 0): compute 1037
 block 1(CPU  0): paste 39
 block 2(CPU  0): copy 320
 block 2(CUDA 0): compute 1040
 block 2(CPU  0): paste 3
 block 3(CPU  0): copy 354
 block 3(CUDA 0): compute 1038
 block 3(CPU  0): paste 1
3 a: -5730 ms.
3 b: -5440 ms.
 block 0(CPU  0): copy 153
 block 0(CUDA 0): compute 1032
 block 0(CPU  0): paste 44
 block 1(CPU  0): copy 187
 block 1(CUDA 0): compute 1229
 block 1(CPU  0): paste 39
4 a: -2831 ms.
4 b: -2609 ms.
iteration: 0 --- sum change: 444220.2861559689 --- max change per pixel: 0.18256843090057373
DONE (Wed Mar 25 15:15:03 CET 2015).
fmax = 0.68843263
fmin = 0.38905355
Wed Mar 25 15:15:06 CET 2015: Saving file /projects/pilot_spim/Christopher/Test_pipeline_3.0/TP2_Ch0_Ill0_Ang1,2,3,4,5.tif
(Wed Mar 25 15:15:12 CET 2015): Fusion finished.

**Comment by StephanPreibisch** [comment]
Hi, I guess it mixes up some name. It is hard for me to test, but I changed the directory tag to "CUDA_Directory", so this should hopefully solve it ... can you try it out? (you would have to build the current version on the command line)

https://github.com/bigdataviewer/SPIM_Registration/commit/9661ee652c548dc61299e78a577e21251fab7def

**Comment by StephanJanosch** [comment]
I'll wait for a proper release. I have not set up a build for the plugin right now.

**Comment by StephanPreibisch** [comment]
git clone https://github.com/bigdataviewer/SPIM_Registration.git
mvn clean package

Or alternatively download it from here: http://jenkins.imagej.net/view/BigDataViewer/job/SPIM_Registration/

**Comment by StephanJanosch** [comment]
It works now. cuda_directory is properly used. Thx.
